import { ToolMeta } from '../types';

export const TOOLS_CONFIG: ToolMeta[] = [
  {
    id: 'username',
    name: 'Username Intelligence',
    description: 'Enumerate accounts and profile namespaces across 25+ web platforms.',
    category: 'Identity',
    accentColor: '#244A73',
    colorName: 'Navy Blue',
  },
  {
    id: 'email',
    name: 'Email Intelligence',
    description: 'Validate syntax, detect disposable providers, audit MX records, and check Gravatar profiles.',
    category: 'Identity',
    accentColor: '#2A7F7F',
    colorName: 'Teal',
  },
  {
    id: 'domain',
    name: 'Domain Intelligence',
    description: 'Investigate domain registration, DoH DNS records, subdomains, and threat indicators.',
    category: 'Network',
    accentColor: '#244A73',
    colorName: 'Navy Blue',
  },
  {
    id: 'dns',
    name: 'DNS Intelligence',
    description: 'Comprehensive DNS over HTTPS lookup, SPF mechanisms audit, and DMARC enforcement review.',
    category: 'Network',
    accentColor: '#2A7F7F',
    colorName: 'Teal',
  },
  {
    id: 'ip',
    name: 'IP Intelligence',
    description: 'Geolocate IPv4/IPv6 addresses, inspect Autonomous System Numbers (ASN), and detect bogon ranges.',
    category: 'Network',
    accentColor: '#244A73',
    colorName: 'Navy Blue',
  },
  {
    id: 'url',
    name: 'URL / Phishing Intelligence',
    description: 'Decompose URL structure, detect homoglyph attacks, typosquatting, and credential lures.',
    category: 'Web & Security',
    accentColor: '#B23A3A',
    colorName: 'Red',
  },
  {
    id: 'website',
    name: 'Website Intelligence',
    description: 'Audit HTTP response security headers, robots directives, server signatures, and SSL policies.',
    category: 'Web & Security',
    accentColor: '#244A73',
    colorName: 'Navy Blue',
  },
  {
    id: 'social',
    name: 'Social Profile Intelligence',
    description: 'Synthesize cross-platform digital footprints, generate username permutations, and map aliases.',
    category: 'Identity',
    accentColor: '#665191',
    colorName: 'Purple',
  },
  {
    id: 'metadata',
    name: 'Metadata Intelligence',
    description: 'Extract binary EXIF tags, GPS telemetry, camera parameters, and sanitize images for OPSEC.',
    category: 'Forensics',
    accentColor: '#665191',
    colorName: 'Purple',
  },
  {
    id: 'hash',
    name: 'Hash Intelligence',
    description: 'Identify hash algorithms, compute SHA/MD5 digests, inspect entropy, and verify threat signatures.',
    category: 'Forensics',
    accentColor: '#3A7D44',
    colorName: 'Green',
  },
  {
    id: 'image',
    name: 'Image Intelligence',
    description: 'Reverse search pivoting, client-side Error Level Analysis (ELA), and RGB color histogram distribution.',
    category: 'Forensics',
    accentColor: '#B7791F',
    colorName: 'Amber',
  },
];
